### ISSUE TITLE
Convert Uint8List to File in Flutter Web

### ISSUE THREAD

**Issue by ShankarKakumani** [speedkodi/flutter_cropperx#15]
After cropping the image, I get UInt8List as result. My API accepts File as input but I am unable to convert the Uint8List into File in Flutter.

any solutions?

**Comment by vidyda** [comment]
I had the same problem

**Comment by ShankarKakumani** [comment]
@vvvdadada, I asked our backend team to change the API to accept base64. I did not found any other solution for this.

**Comment by shannon-rodricks** [comment]
If youre using multipart form, you can send it as 
```
MultipartFile.fromBytes(
          bytes,
          filename: "<filename>",
          contentType: MediaType("image", "png"),
        )
```
Else you can convert it back to an image using
```
//since the library encodes the bytes as png
image.decodeNamedImage("$path.png", bytes);
```
and then save it to a file (not sure how you do that in web though)
