### ISSUE TITLE
Update package to Flutter 3.0 compatible

### ISSUE THREAD

**Issue by gorkemsari** [speedkodi/flutter_cropperx#9]
../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/cropperx-1.0.0/lib/cropperx.dart:95:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

../../Applications/flutter/.pub-cache/hosted/pub.dartlang.org/cropperx-1.0.0/lib/cropperx.dart:215:20: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.

**Comment by gorkemsari** [comment]
@speedkodi

**Comment by ThomasMiddel** [comment]
Fixed in version 1.1.0! Thanks for the quick notice 🙏
